baseURL = "https://KomadaKeigo.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "docs"
theme = "aafu"

[build]
  writeStats = true

[params]
    title = "MainPage:Keigo Komada(Tohoku Univ.)/駒田啓伍(東北大学)"
    author = "Keigo Komada"
    description = "Website title"
    copyright = "© 2023 Keigo Komada"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "ocean"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        #images/icons/default/"
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="images/icons/slime/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="images/icons/slime/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="images/icons/slime/favicon-16x16.png">
        <link rel="manifest" href="images/icons/slime/site.webmanifest">
        <link rel="mask-icon" href="images/icons/slime/safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="images/icons/slime/favicon.ico">
        '''
        
        # metas = '''
        # <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        # <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        # <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        # <link rel="manifest" href="site.webmanifest">
        # <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        # <link rel="shortcut icon" href="favicon.ico">
        # '''

    # Profile section
    [params.profile]
        name = "Keigo Komada"
        tagline = "駒田 啓伍"
        location = "Tohoku NLP Group"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "#"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-stack-overflow"
            url = "#"
            title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "#"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "#"
            title = "Twitter"
        [[params.social.list]]
            icon = "fab fa-orcid"
            url = "#"
            title = "Orcid"
        [[params.social.list]]
            icon = "ai ai-google-scholar"
            url = "#"
            title = "Google Scholar"
        [[params.social.list]]
            icon = "fab fa-researchgate"
            url = "#"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "contact_details"
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "4th year student of Tohoku University Department of Electrical Information and Physics Engineering, Tohoku NLP Group"
    
    [params.contact_details]
        title = "Contact Details"
        icon = "fa fa-phone"#"fa-solid fa-phone"
        [[params.contact_details.list]]
        address_name = "Mail"
        address_content = "keigo.komada.r6@gmail.com"
        

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Job Title"
            dates = "2019 - *Present*"
            company = "Company Name"
            details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
        [[params.experience.list]]
            position = "Job Title"
            dates = "2018 - 2019"
            url = "#"
            company = "Company Name"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        # [[params.education.list]]
        #     degree = "Ph.D. in Subject"
        #     college = "University of State-City"
        #     dates = "2013 - 2018"
        #     thesis_title = "Effect of humans on other humans: a study of human behavior."
        #     thesis_url = "#"
        # [[params.education.list]]
        #     degree = "M.S. in Subject"
        #     college = "University of State-City"
        #     dates = "2013 - 2018"
        #     thesis_title = "Effect of humans on other humans: a study of human behavior."
        #     thesis_url = "#"
        [[params.education.list]]
            degree = "B.S. in Information Science"
            college = "Tohoku University"
            dates = "2019 - 2023"
        [[params.education.list]]
            degree = "High School"
            college = "Sendai Third High School"
            dates = "2016 - 2019"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        # [[params.publication.list]]
        #     title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        #     authors = "F Last, F Second, P secondary"
        #     date = "2018"
        #     journal = "Journal of Field 52 (16), 9033-9044"
        #     url = "#"
        #     type = "Journal Articles"

        # [[params.publication.list]]
        #     title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        #     authors = "F Last, F Second, P secondary"
        #     date = "2018"
        #     journal = "Journal of Field 52 (16), 9033-9044"
        #     url = "#"
        #     type = "Journal Articles"
		
        # [[params.publication.list]]
        #     title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        #     authors = "F Last, F Second, P secondary"
        #     date = "2018"
        #     journal = "Journal of Field 52 (16), 9033-9044"
        #     url = "#"
        #     type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "NLP 100 Knock"
            url = "https://nlp100.github.io/ja/"
            description = "Learning programming skills for research activities"
        [[params.project.list]]
            title = "Learning Fundamentals of NLP"
            url = "https://www.nlp.ecei.tohoku.ac.jp/study-groups/learning-fundamentals-of-nlp/"
            description = "Learning fundamental NLP methods"
        # [[params.project.list]]
        #     title = "Project 3"
        #     url = "#"
        #     description = "Description of the project"
        # [[params.project.list]]
        #     title = "Project 4"
        #     url = "#"
        #     description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python : fluent"
            skillrating = 70
        [[params.skill.list]]
            skill = "C# : fluent"
            skillrating = 80
        [[params.skill.list]]
            skill = "Unity : intermediate"
            skillrating = 50
        [[params.skill.list]]
            skill = "English/TOEIC : 705"
            skillrating = 71

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Developing Game"
        [[params.hobby.list]]
            hobby = "Playing Game"
        [[params.hobby.list]]
            hobby = "Cooking"